server:
  port: 0

logging:
  level:
    org:
      springframework:
        data=TRACE:

#spring:
#  data:
#    mongodb:
#      database:
#      host: localhost
#      port: 27017
#spring:
#  webflux:
#    hiddenmethod:
#      filter:
#        enabled: true